-- phpMyAdmin SQL Dump
-- version 4.1.12
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Dec 28, 2016 at 07:22 PM
-- Server version: 5.6.16
-- PHP Version: 5.5.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `subhojit`
--

-- --------------------------------------------------------

--
-- Table structure for table `subhojits_poems`
--

CREATE TABLE IF NOT EXISTS `subhojits_poems` (
  `id` int(5) NOT NULL AUTO_INCREMENT,
  `photos` varchar(255) NOT NULL,
  `poemname` varchar(255) NOT NULL,
  `genre` varchar(255) NOT NULL,
  `lines_info` varchar(2000) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=105 ;

--
-- Dumping data for table `subhojits_poems`
--

INSERT INTO `subhojits_poems` (`id`, `photos`, `poemname`, `genre`, `lines_info`) VALUES
(45, '1482933239.jpg', 'Subhecha', 'Birthday Wish', 'Wished one of my good friends to his birthday. \r\nThis is written in Bengali Language.\r\nA wish of the realization which is expressed as the day and his parents.'),
(46, '1482933987.', 'Reality thoughts', 'Forgiven Reality', 'Sometimes, I feel bad for those who never stop being proud of themselves,\r\nSometimes, some cheerful moments give me hope to keep a little bit faith in myselfâ€¦ At times, this God-gifted nature tells our desire to stop the clock for eternity,\r\nNevermind the activity of our precious heart & thoughts of brain, ensuring the fate emerges with sanityâ€¦.\r\nSome of you have understood these lines & some of you are keep pretending it as â€œblown above the headâ€!\r\nAnd the rest are busy finding different meanings of the lines that I have written just now, to grow it older than being fedâ€¦\r\nSome beings see reality as a toy of creation with being â€œself-caringâ€!\r\nUntil the situation asks them,      â€œif you would be in my position, what would you be feeling?â€'),
(47, '1482934255.jpg', 'Joy of Clouds!', 'Megheder Uchas!', 'This poem is written keepin in mind the Rain & Clouds.\r\nThey are always good as a rainy day is still an enjoying day to us.'),
(49, '1482935052.jpg', 'Weather ', 'Nature of Life', 'There is pleasure in the pathless woods, there is rapture in the lonely shore, there is society where none intrudes, by the deep sea, and music in its roar; I love not Man the less, but Nature more.'),
(50, '1482935151.jpg', 'With a bottle!', 'Meaning of Life', 'The third is to find a balance between the two â€“ between living your individual life to the fullest, while striving to help humanity evolve to a higher consciousness of compassion, meaning and purpose. To freely bloom - that is my definition of success.'),
(51, '1482935394.jpg', 'Hardship', 'Success of Hardship!', 'Let every nation know, whether it wishes us well or ill, that we shall pay any price, bear any burden, meet any hardship, support any friend, oppose any foe to assure the survival and the success of liberty.'),
(52, '1482935503.jpg', 'Up above the sky!', 'Flying Kites', 'Throw your dreams into space like a kite, and you do not know what it will bring back, a new life, a new friend, a new love, a new country.'),
(53, '1482935894.jpg', 'Superior of Eternity!', 'Strength of Comeback!', 'Given the nature of sports, its not surprising that athletes have had some inspiring and motivational things to say about hard work, leadership, perseverance, winning, and much more. Here are the top 100 most motivational sports quotes in history\r\n\r\nâ€œThe only way to prove that youâ€™re a good sport is to lose.â€\r\nâ€“ Ernie Banks\r\n\r\nâ€œOnly he who can see the invisible can do the impossible.â€\r\nâ€“ Frank L. Gaines\r\n\r\nâ€œWhen youâ€™re riding, only the race in which youâ€™re riding is important.â€\r\nâ€“ Bill Shoemaker'),
(54, '1482936392.jpg', 'Wo kabhi rukte nahi ...', 'Barish aur waqt!', 'Barish hota ha tab jab badal nahi garajta,\r\nAsman chamakta ha tab jab roshni nahi raheta,	\r\nWaqt rukta nahi khud\r\njab use rukneme na ho koi faeda,\r\naur Dil samajhta ha tab jab waqt me rosni ka ho basera...'),
(55, '1482936539.jpg', 'Light from him ...', 'Fact of Light!', 'When the Light prevail the path to be expected,\r\nClouded morning creating wheel of unexpected!\r\nFaith of art is making joy in the shining ray,\r\nShielded thought is getting us in the learning way...'),
(56, '1482936681.jpg', 'Friends of Life ...', 'A wish from a Friend', 'When we are happy, we want to share our happiness with someone close and dear to our heart, because we know that itâ€™ll make him happy too. When we are upset, we also want to share our sadness with someone whoâ€™s able to change our mood for the better. And this someone is the best friend.'),
(57, '1482936827.jpg', 'Climate says ...', 'Matter of Weather', 'Nevertheless, there is another threat on the horizon. I see this threat in environmentalism which is becoming a new dominant ideology, if not a religion. Its main weapon is raising the alarm and predicting the human life endangering climate change based on man-made global warming.'),
(58, '1482937011.jpg', 'Festive Ways ...', 'Parted Believes ...', 'Today I begin to understand what love must be, if it exists... When we are parted, we each feel the lack of the other half of ourselves. We are incomplete like a book in two volumes of which the first has been lost. That is what I imagine love to be: incompleteness in absence. \r\n\r\nWhen from our better selves we have too long been parted by the hurrying world, and droop. Sick of its business, of its pleasures tired, how gracious, how benign is solitude. \r\n'),
(59, '1482937335.jpg', 'Festive thoughts ...', 'Combination of Thoughts', 'History teaches us that unity is strength, and cautions us to submerge and overcome our differences in the quest for common goals, to strive, with all our combined strength, for the path to true African brotherhood and unity. \r\n\r\nA multitude of causes unknown to former times are now acting with a combined force to blunt the discriminating powers of the mind, and unfitting it for all voluntary exertion to reduce it to a state of almost savage torpor. \r\n'),
(60, '1482937476.jpg', 'Temple of Living Life ...', 'Phase of Lives ', 'â€œThis is my simple religion. There is no need for temples; no need for complicated philosophy. Our own brain, our own heart is our temple; the philosophy is kindness.â€ \r\nâ€• Dalai Lama XIV, The Dalai Lama: A Policy of Kindness: An Anthology of Writings By and About the Dalai Lama\r\n\r\nâ€œWe are his temple. We do not turn in a certain directlon to pray. We are not bound by having to go into a building so that we can commune with God. There are no unique postures and times and limitations that restrict our access to God. My relationship with God is intimate and personal. The Christian does not go to the temple to worship. The Christian takes the temple with him or her. Jesus lifts us beyond the building and pays the human body the highest compliment by making it His dwelling place, the place where He meets with us. Even today He would overturn the tables of those who make it a marketplace for their own lust, greed, and wealth.â€ \r\nâ€• Ravi Zacharias, Jesus Among Other Gods: The Absolute Claims of the Christian Message'),
(61, '1482938306.jpg', 'Badalte huye ye waqt ...', 'waqt rukta nahi khud', 'Badalte huye ye waqt nikharte nahi kabhi,\r\nBadalte huye yehi waqt rukti nahi kabhi...\r\nZindagi yaad dilati hai un guzarti huye pal ko,\r\nJisme Guzarte huye is waqt ki koi rukawat na ho...\r\nAj barsaat ke is mausam ka kuch to hai ishara,\r\nPar isharo ke agee vi ratoka hai andhera...\r\nJaha Sachai chupti nahi kabhi jhut ke achal pe,\r\nWaha achai basti ha khud din ke ujalo pe...'),
(62, '1482938388.jpg', 'Janalar Kone,', 'In the Corner of the Window...', 'thanda hawar sroter kone\r\nmoner shitalata,\r\njiban sroter manthane j\r\nabak gobhirata,\r\nshital moner joarete\r\nuchashito smriti,\r\nrater komal abohete\r\njibanto ae prakriti...'),
(63, '1482938500.jpg', 'When there is Smile...', 'There is Happiness...', 'Today I choose life. Every morning when I wake up I can choose joy, happiness, negativity, pain... To feel the freedom that comes from being able to continue to make mistakes and choices - today I choose to feel life, not to deny my humanity but embrace it.'),
(64, '1482938927.jpg', 'Shores of the Ocean...', 'Leads to an end ...', 'â€œYou do not have to be good.\r\nYou do not have to walk on your knees\r\nfor a hundred miles through the desert, repenting.\r\nYou only have to let the soft animal of your body \r\nlove what it loves.\r\nTell me about despair, yours, and I will tell you mine.\r\nMeanwhile the world goes on.\r\nMeanwhile the sun and the clear pebbles of the rain\r\nare moving across the landscapes,\r\nover the prairies and the deep trees,\r\nthe mountains and the rivers.\r\nMeanwhile the wild geese, high in the clean blue air,\r\nare heading home again.\r\nWhoever you are, no matter how lonely,\r\nthe world offers itself to your imagination,\r\ncalls to you like the wild geese, harsh and exciting â€“\r\nover and over announcing your place\r\nin the family of things.â€ \r\nâ€• Mary Oliver'),
(65, '1482939254.jpg', 'Writing something ...', 'Expecting something?', 'The reason this country continues its drift toward socialism and big nanny government is because too many people vote in the expectation of getting something for nothing, not because they have a concern for what is good for the country. '),
(66, '1482941672.jpg', 'Thoughts from Hope...', 'Treasure of Beliefs', 'Shield of thoughts are making joy,\r\nLots of thinkers are begging for toy...\r\nLearning mind is taking much time,\r\nDay is simple as clear sunshine...!\r\nTree of life is making us laugh,\r\nDream of night is growing it rough!\r\nField of work is giving us a try,\r\nRay of hope says â€œnever Good-byeâ€!\r\n\r\nSubhojit'),
(67, '1482942278.jpg', 'Untied Justice', 'Law & Order', 'Price is worthless, mind is fine,\r\nCoins are hopeless, eyes are guide.\r\nLittle bit taste of Love gives health,\r\nShit of tasks are rounding up wealth!\r\nEnormous guides of fight need rest,\r\nFuture of chaos is still at its best!\r\nUntied bonds are again getting tied,\r\nUnreal Justice is now verifiedâ€¦.\r\n'),
(68, '1482942477.jpg', 'Bitey huye dine...', 'Lamhe bitte ha...', 'Price is worthless, mind is fine,\r\nCoins are hopeless, eyes are guide.\r\nLittle bit taste of Love gives health,\r\nShit of tasks are rounding up wealth!\r\nEnormous guides of fight need rest,\r\nFuture of chaos is still at its best!\r\nUntied bonds are again getting tied,\r\nUnreal Justice is now verifiedâ€¦.\r\n'),
(69, '1482942643.jpg', 'Palace of God', 'Temple of Peace', 'No Temple made by mortal human hands can ever compare to the Temple made by the gods themselves. That building of wood and stone that houses us and that many believe conceals the great Secret Temple from prying eyes, somewhere in its heart of hearts, is but a decoy for the masses who need this simple concrete limited thing in their lives. The real Temple is the whole world, and there is nothing as divinely blessed as a blooming growing garden.'),
(70, '1482943375.jpg', 'Myths of Life', 'Where Myths are Real ...', 'Facts of life are going high,\r\nEast or West, all in sigh!\r\nMyths are taking the breath from lie,\r\nOur needs are making tieâ€¦\r\nLove is life to live in sky,\r\nComplex thoughts are making us cryâ€¦\r\nLevel of freedom is telling bye,\r\nWe need air to tell all hiâ€¦!'),
(71, '1482943579.', 'Forgiven Reality', 'Reality thoughts', 'Facts of life are going high,\r\nEast or West, all in sigh!\r\nMyths are taking the breath from lie,\r\nOur needs are making tieâ€¦\r\nLove is life to live in sky,\r\nComplex thoughts are making us cryâ€¦\r\nLevel of freedom is telling bye,\r\nWe need air to tell all hiâ€¦!\r\n'),
(72, '1482943769.jpg', 'Kolpito Bastob', 'Feelings of Reality', ''),
(73, '1482944016.', 'Barish me basee lamho ki dastak', 'Pr wo akhein kabhi ye samjhte nahi ...', 'Sham ki hatheli pe barish ki tanhai,\r\nJaha ishq bezubaan ha leke badalo ki parchaiâ€¦\r\nShishe pe likhe taqdir ka rang jab sachai se leti ha rishwat,\r\nBadalo me chupe suraj ke sang tab barish deti ha dastakâ€¦\r\nDin me chaye andhere me lamho ki ha shikayat,\r\nPani me dube huye rah me,chahat ki ha ibadatâ€¦\r\nYe dil dharakna chahta ha kisi or k liye roshni ki khwab lekar,\r\nPar wo akhe kabhi ye samajhte nahi gujre huye waqt ki dua ban karâ€¦'),
(74, '1482944095.jpg', 'Zindagi ki Khawaisho me...', 'Jab waqt ka ho sahara', 'Zindagi ki khawaisho me\r\njab waqt ka ho sahara,\r\nLamho ki duniya me\r\ntab sapne ka ho basera...\r\npal \r\ngujarti ha tab jab usme roshni ka ho chahat!\r\naur mohabbat\r\nuvalti ha tab jab usme uljhano ki ho rahat....'),
(76, '1482944462.jpg', 'Megher parosh biday nilo...', 'Siter amej fute uthlo', 'Megher parosh biday nilo,\r\nSiter amej fute uthlo,\r\nGhumer ghore katena r din,\r\nProkitir monorom abohe mon hoilo bilin...'),
(77, '1482944552.jpg', 'You want Perfection?', 'Ask Yourself!', 'It is quiet understanding, mutual confidence, sharing and forgiving. It is loyalty through good and bad times. It settles for less than perfection and makes allowances for human weaknesses. Success is the result of perfection, hard work, learning from failure, loyalty, and persistence.'),
(80, '1482945147.jpg', 'Shadows of Memory', 'Shades', 'Where the mind is without fear ...'),
(81, '1482945215.jpg', 'Comrades...', 'Soul Mates', 'Treasure Moments...'),
(83, '1482945628.', 'à¦¸à¦®à§Ÿ à¦¯à¦–à¦¨ à¦à¦—à¦¿à§Ÿà§‡ à¦šà¦²à§‡...', 'à¦¬à¦¾à¦¸à§à¦¤à¦¬', 'à¦¸à¦•à¦¾à¦²-à¦¦à§à¦ªà§à¦°-à¦¬à¦¿à¦•à¦¾à¦²à¦¬à§‡à¦²à¦¾,\r\nà¦šà¦²à¦›à§‡ à¦¶à§à¦§à§à¦‡ à¦ªà¦¾à¦¶à¦¾à¦° à¦–à§‡à¦²à¦¾ à¥¤\r\nà¦­à¦¬à¦¿à¦·à§à¦¯à¦¤à§‡à¦° à¦†à¦¶à¦¾à§Ÿ à¦¬à¦¸à§‡,\r\nà¦•à§à¦²à¦¾à¦¨à§à¦¤ à¦ à¦®à¦¨ à¦®à¦¿à¦šà¦•à¦¿ à¦¹à¦¾à¦¸à§‡ à¥¤\r\nà¦šà¦²à¦¾à¦° à¦ªà¦¥à§‡ à¦à¦•à¦Ÿà§ à¦†à¦²à§‹,\r\nà¦¬à¦²à¦›à§‡ à¦¹à§‡à¦à¦•à§‡,â€œà¦à¦—à¦¿à§Ÿà§‡ à¦šà¦²à§‹â€!\r\nà¦°à¦¾à¦¤à§à¦°à¦¿ à¦à¦¸à§‡ à¦¬à¦²à¦›à§‡ à¦®à¦¾à¦à§‡,\r\nâ€œà¦—à¦¤à¦¿ à¦¬à¦¾à§œà¦¾à¦“, à¦à¦•à¦Ÿà§ à¦¥à§‡à¦®à§‡â€à¥¤\r\nÂ \r\nà¦¨à¦¿à¦®à§‡à¦·à§‡ à¦¤à¦¾à¦‡ à¦¸à§‚à¦°à§à¦¯à§‡à¦° à¦‰à¦¦à§Ÿ,\r\nà¦•à¦¾à¦Ÿà¦›à§‡ à¦¨à¦¾ à¦ à¦¦à§€à¦°à§à¦˜à¦¸à¦®à§Ÿ à¥¤\r\nà¦¬à¦°à§à¦¤à¦®à¦¾à¦¨à§‡à¦° à¦¬à§à¦¯à¦°à§à¦¥ à¦…à¦¤à§€à¦¤,\r\nà¦•à¦¿ à¦•à¦°à§‡ à¦¯à§‡ à¦²à¦¿à¦–à¦›à§‡ à¦¸à¦ à¦¿à¦•?\r\nà¦†à¦œ à¦¨à¦¿à¦ƒà¦¸à§à¦¬ à¦®à¦¨à§‡à¦° à¦¨à¦¿à¦°à§à¦¬à¦²à¦¤à¦¾,\r\nà¦¦à§‡à¦–à¦›à§‡ à¦•à§‡à¦¬à¦² à¦…à¦•à§à¦·à¦®à¦¤à¦¾!\r\nà¦¤à¦¾à¦‡ à¦à¦‡ à¦¨à¦¿à¦°à¦¾à¦¶ à¦†à¦à¦§à¦¾à¦°, à¦œà§€à¦°à§à¦£ à¦†à¦²à§Ÿ,\r\nà¦®à§‡à¦²à§‡ à¦šà¦¾à¦¦à¦°, à¦¸à¦¾à¦§à¦›à§‡ à¦¬à¦¿à¦¨à§Ÿ à¥¤\r\n\r\n'),
(84, '1482945737.jpg', 'When together we are...', 'Dreams of The Anarchy!', 'The time you feel lonely is the time you most need to be by yourself.'),
(85, '1482945821.jpg', 'Day of Night', 'Nature of Time', 'Night turns Day and Day turns Night,\r\nNever mind my theory, just makes guide.\r\nLittle bit of Ray is the cause of Light,\r\nAnd a little bit of Light is the end of Night!\r\n\r\nThe similar way the Dark makes path,\r\nTypical mind makes the timing rough.\r\nDawn comes in way to end Dark thus,\r\nFight of Love gets victory with rush.\r\n\r\nThanks for Reading this Lines of Mine,\r\nKeep Making Joy and Happiness by Shine.'),
(86, '1482946015.jpg', 'à¦®à§à¦•à§à¦¤à¦¦à¦¿à¦¨à§‡à¦° à¦†à¦¶à¦¾à§Ÿ ', 'Freedom of Hope...', 'à¦¸à§‚à¦°à§à¦¯ à¦¯à¦¤à¦‡ à¦¤à§‡à¦œ à¦¦à§‡à¦–à¦¾à¦•!\r\nà¦¬à§ƒà¦·à§à¦Ÿà¦¿ à¦à¦•à¦¦à¦¿à¦¨ à¦¬à¦¾à¦œà¦¾à¦¬à§‡ à¦¶à¦¾à¦à¦–à¥¤\r\nà¦¸à§‡à¦¦à¦¿à¦¨, à¦šà¦²à¦¬à§‡ à¦¬à¦¾à¦¤à¦¾à¦¸,à¦¨à¦¾à¦šà¦¬à§‡ à¦†à¦•à¦¾à¦¶,\r\nà¦ªà¦¥à§‡à¦° à¦¸à¦¾à¦¥à§€à¦°à¦¾ à¦ªà¦¾à¦¬à§‡ à¦¯à§‡ à¦¶à§à¦¬à¦¾à¦¸!\r\nà¦†à¦œ, à¦•à¦¾à¦²à¦¬à§ˆà¦¶à¦¾à¦–à§€à¦° à¦›à¦¦à§à¦®à¦¬à§‡à¦¶à§‡,\r\nà¦²à§ à¦¬à¦‡à¦›à§‡ à¦¤à¦¾à¦¸à§‡à¦° à¦¦à§‡à¦¶à§‡à¥¤\r\nà¦¤à¦¾à¦“ à¦®à§Œà¦¸à§à¦®à§€ à¦šà¦¾à§Ÿ à¦¦à¦¿à¦• à¦¦à§‡à¦–à¦¾à¦¤à§‡,\r\nà¦†à¦¶à¦¾à¦° à¦¬à§‡à¦¶à§‡ à¦°à¦¾à¦¤-à¦¬à¦¿à¦°à§‡à¦¤à§‡!\r\n\r\nà¦à¦¦à¦¿à¦•à§‡ à¦­à§‹à¦Ÿ à¦¬à¦²à¦›à§‡, à¦†à¦®à¦¾à§Ÿ à¦¦à¦¿à¦¸!\r\nà¦¯à§‡à¦¦à¦¿à¦•à§‡ à¦šà¦¾à¦‡, à¦¶à§à¦§à§à¦‡ à¦¬à¦¿à¦·!\r\nà¦­à¦¾à¦² à¦¦à¦¿à¦¨à§‡à¦° à¦®à§à¦•à§à¦¤ à¦•à¦¥à¦¾à§Ÿ,\r\nà¦­à§à¦² à¦­à§‹à¦²à¦¾à¦¤à§‡ à¦®à¦¾à¦¨à§à¦· à¦ à¦•à¦¾à§Ÿà¥¤\r\nà¦¨à¦¾à¦°à¦¦à¦¾,à¦¸à¦¾à¦°à¦¦à¦¾ à¦¸à¦¬à¦‡ à¦†à¦›à§‡,\r\nà¦¤à¦¾à¦“ à¦¨à§à¦¯à¦¾à§œà¦¾à¦¦à§‡à¦° à¦®à¦¤à¦¿ à¦¨à¦¾ à¦«à§‡à¦°à§‡! \r\nà¦¶à§‡à¦·à§‡ à¦‰à§œà¦¾à¦²à¦ªà§à¦² à¦“ à¦›à¦¾à§œà¦² à¦†à¦¶à¦¾,\r\nà¦¬à¦‡à¦² à¦ªà¦¥à§‡ à¦°à¦•à§à¦¤à¦§à¦¾à¦°à¦¾à¥¤\r\nà¦¦à§à¦²à¦›à§‡ à¦°à¦¾à¦œà§à¦¯ à¦¡à¦¿à¦™à§à¦—à¦¿à§Ÿà§‡ à¦¸à¦¾à¦—à¦°,\r\nà¦¦à¦¿à¦•-à¦¬à¦¿à¦¦à¦¿à¦•à§‡ à¦¸à¦¾à¦œà¦¿à§Ÿà§‡ à¦ªà¦¾à¦¥à¦°à¥¤\r\nà¦¤à¦¿à¦°à¦¿à¦¶-à¦¦à¦¶à¦• à¦¤à§à¦¤ à¦šà¦²à§‡à¦›à§‡ à¦¶à¦¾à¦¸à¦¨,\r\nà¦šà¦¾à¦‡à¦›à§‡ à¦®à¦¾à¦¨à§à¦·, à¦¦à§‡à¦¬à§‡à¦¨ à¦†à¦¸à¦¨? '),
(87, '1482946103.jpg', 'Engineering is ...', 'Where The Night before Exam is the Day of Learning ...', ''),
(88, '1482946305.jpg', 'Fly high in the sky', 'Dive through the sky', ''),
(89, '1482946397.jpg', 'Comrades...', 'Soul-Mates', 'Day of the Agents ...'),
(92, '1482946629.jpg', 'Moments of Life', 'Memories and Fun!', ''),
(93, '1482946766.jpg', 'Day of Independence', 'The day of Freedom...', 'Forget not that the grossest crime is to compromise with injustice and wrong. Remember the eternal law: you must give, if you want to get. - Netaji Subhash Chandra Bose\r\n\r\nRevolution is an inalienable right of mankind. Freedom is an imperishable birth right of all. Labour is the real sustainer of society, the sovereignty of the ultimate destiny of the workers. - Bhagat Singh'),
(94, '1482947005.jpg', 'Pencil of Calmness', 'Realization of Necessity', ''),
(96, '1482947253.jpg', 'Love of Faith', 'with a message...', 'What I have denied and what my reason compels me to deny, is the existence of a Being throned above us as a god, directing our mundane affairs in detail, regarding us as individuals, punishing us, rewarding us as human judges might.'),
(97, '1482947430.jpg', 'Never Give up!', 'Keep Faith...', 'God gave us the gift of life; it is up to us to give ourselves the gift of living well. '),
(98, '1482947557.jpg', 'Verified Love', 'Treasure of Beliefs', 'Itâ€™s in our nature to want to watch our human frailties played out on a huge, epic canvas. Ancient societies had anthropomorphic gods: a huge pantheon expanding into centuries of dynastic drama: fathers and sons, star-crossed lovers, warring brothers, martyred heroes. Tales that taught us the danger of hubris and the primacy of humility. Itâ€™s the everyday stuff of everymanâ€™s life, but itâ€™s writ large, and we love it.'),
(99, '1482947607.jpg', 'Maker of Real Things', 'Similar Faiths', 'And then it occurs to me. They are frightened. In me, they see their own daughters, just as ignorant, just as unmindful of all the truths and hopes they have brought to America. They see daughters who grow impatient when their mothers talk in Chinese, who think they are stupid when they explain things in fractured English. They see that joy and luck do not mean the same to their daughters, that to these closed American-born minds "joy luck" is not a word, it does not exist. They see daughters who will bear grandchildren born without any connecting hope passed from generation to generation.'),
(100, '1482947765.jpg', 'Perfection Leads...', 'Agree?', 'Always dream and shoot higher than you know you can do. Do not bother just to be better than your contemporaries or predecessors. Try to be better than yourself.'),
(101, '1482947914.jpg', 'Where there is Comeback', 'There is the word "Bounce back...!"', ''),
(102, '1482947982.jpg', 'When You are Greater than yourself', 'Life makes its own way ...', ''),
(103, '1482948013.jpg', 'Beauty of Face', 'Eyes with a message...', ''),
(104, '1482948308.jpg', 'Christmas Eve with some Cake...', 'Merry Christmas', 'Christmas! Christmas! Santa came on dream,\r\nLiteral thoughts are making mind clean!\r\nNicholas is on the ride, with toys and gifts,\r\nRudolph gets above the Moon and lightened firs.\r\n\r\nDrifter of Real time never leaves clock,\r\nReindeer are on the run, surpassing every block.\r\nLiving by the North Pole, the Saint of Myra,\r\nLove of the little children, tells "sayonara".\r\n\r\nBirthday of Jesus feels, have some cake!\r\nMouth gets cold enough to make some shake.\r\nThis is called the great day where night is long,\r\nLittle brains, growing minds â€“ dont take it wrong!\r\n\r\nHoliday is saying God, â€œPlay your Showâ€,\r\nSanta be like hearing that, "ho! ho! ho!"\r\n');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
